<!-- i m in message -->
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>message</title>
</head>

<body>
	<?php
	$messages = new Model_Core_Message();
	$tempMessage= $messages->getMessages();

	 if(isset($tempMessage['success'])){
		echo  '<div class="alert alert-success">'.$tempMessage['success'].'!</div>';
	}
	if(isset($tempMessage['failure'])){
		echo '<div class="bg-danger">'.$tempMessage['failure'].'!</div>';
	}
	
	if(isset($tempMessage['warning'])){
		echo '<div class="bg-warning">'.$tempMessage['warning'].'!</div>';
	}
	 	$messages->cleanMessages();
?>


</body>
</html>