<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>add image</title>
</head>
<body>
		<form action="<?php echo $this->getUrl()->getUrl('product_media','insert');?>" method="POST"  enctype="multipart/form-data"> 

<h2 style="margin-top: 60px;">ADD IMAGE</h2>

			 
			<table>
				
				<tr>
					<th>Browse image</th>
					<td><input type="file" id="image" name="image"></td>
				</tr>
				<tr>
					<td>Image_Name</td>
					<td><input type="text" name="filename"></td>
				</tr>
				<tr>
					<td>
					<button style="margin-top: 50px; margin-left: 50px;" name="submit" type="submit">SAVE </button>
				</td>
				</tr>
			</table>

		</form>

</body>
</html>