 <?php
$result = $this->shipping;
?> 

	<form action="<?php echo $this->getUrl('shipping','save');?>" method="POST">
		<table width="20%">
			<tr>
				<td><h3>Edit Shipping</h3></td>
				<td><button class="btn btn-primary">SAVE</button></td>
			</tr>
		</table>
		<table>
			 
			<tr>
				<td>ShippingId :</td>
				<td><input type="number" name="shipping[shipping_id]" value="<?php echo $result->shipping_id;?>"></td>
			</tr>
			<tr>
				<td>NAME :</td>
				<td><input style="width:100%" type="text" name="shipping[name]" value="<?php echo $result->name;?>"></td>
			</tr>
			<tr>
				<td>Amount :</td>
				<td><input type="text" name="shipping[amount]" value="<?php echo $result->amount;?>"></td>
			</tr>
			<tr>
					<th> Status</th>
					<td> <select name="shipping[status]" >
						<?php foreach ($result->getResource()->getStatusOptions() as $key => $value): ?>
						<option value="<?php echo $key ?>"><?php echo $value ?></option>
						<?php endforeach; ?>
						
					</select> </td>
				</tr>
			
			
			 
		</table>
	</form>

