<?php
	$result=$this->address;
?> 

			<tr>
				<td><h3>Vendor Address</h3></td>
			</tr>
		
		
			<tr>
				<td>Address :</td>
				<td><input type="text" name="vendorAdd[address]" value="<?php echo $result->address;?>"></td>
			</tr>
			<tr>
				<td>City :</td>
				<td><input type="text" name="vendorAdd[city]" value="<?php echo $result->city;?>"></td>
			</tr>
			<tr>
				<td>State :</td>
				<td><input type="text" name="vendorAdd[state]" value="<?php echo $result->state;?>"></td>
			</tr>
			<tr>
				<td>Country :</td>
				<td><input type="text" name="vendorAdd[country]" value="<?php echo $result->country;?>"></td>
			</tr>
			<tr>
				<td>ZipCode :</td>
				<td><input type="text" name="vendorAdd[zipcode]" value="<?php echo $result->zipcode;?>"></td>
			</tr>
			<tr>
				<td>Customer_id :</td>
				<td>
					  <input type="text" name="vendorAdd[vendor_id]" value="<?php echo $result->vendor_id;?>"> 
				</td>
		 	</tr>
	