<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>2column</title>
</head>
<body>
<table border="1" width="100%">
	<tr>
		<td colspan="3" height="80px">HEADER </td>
	</tr>
	<tr>
		<td colspan="3" height="40px"> MESSAGE</td>
		
	</tr>
	<tr>
		<td colspan="3" height="250px">	<?php $this->getChild('content')->render(); ?>
 </td>
		
	</tr>
	<tr>
		<td colspan="3" height="80px"> FOOTER</td>
		
	</tr>
	</table>
</body>
</html>