<?php
	$result=$this->createChild();
?> 

			<tr>
				<td><h3>CustomerAddress</h3></td>
			</tr>
		
			
			<tr>
				<td>Address :</td>
				<td><input type="text" name="customerAdd[address]" value="<?php echo $result->address;?>"></td>
			</tr>
			<tr>
				<td>City :</td>
				<td><input type="text" name="customerAdd[city]" value="<?php echo $result->city;?>"></td>
			</tr>
			<tr>
				<td>State :</td>
				<td><input type="text" name="customerAdd[state]" value="<?php echo $result->state;?>"></td>
			</tr>
			<tr>
				<td>Country :</td>
				<td><input type="text" name="customerAdd[country]" value="<?php echo $result->country;?>"></td>
			</tr>
			<tr>
				<td>ZipCode :</td>
				<td><input type="text" name="customerAdd[zip_code]" value="<?php echo $result->zip_code;?>"></td>
			</tr>
			
		 	</tr>
	