<?php
	$result=$this->address;
?> 

			<tr>
				<td><h3>Salesman Address</h3></td>
			</tr>
		
		
			<tr>
				<td>Address :</td>
				<td><input type="text" name="salesmanAdd[address]" value="<?php echo $result->address;?>"></td>
			</tr>
			<tr>
				<td>City :</td>
				<td><input type="text" name="salesmanAdd[city]" value="<?php echo $result->city;?>"></td>
			</tr>
			<tr>
				<td>State :</td>
				<td><input type="text" name="salesmanAdd[state]" value="<?php echo $result->state;?>"></td>
			</tr>
			<tr>
				<td>Country :</td>
				<td><input type="text" name="salesmanAdd[country]" value="<?php echo $result->country;?>"></td>
			</tr>
			<tr>
				<td>ZipCode :</td>
				<td><input type="text" name="salesmanAdd[zipcode]" value="<?php echo $result->zipcode;?>"></td>
			</tr>
			<tr>
				<td>Customer_id :</td>
				<td>
					  <input type="text" name="salesmanAdd[salesman_id]" value="<?php echo $result->salesman_id;?>"> 
				</td>
		 	</tr>
	