<?php
$salesmanAdd = $this->address;
?>


<table class="table table-bordered table-hover w-100">
	<tr>
		<th>Address_id</th>
		<th>Address</th>
		<th>City</th>
		<th>State</th>
		<th>Country</th>
		<th>Zip_code</th>
		<th>Salesman_id</th>

	</tr>
		 
	<tr>
		<td><?php echo $salesmanAdd->address_id;?></td>
		<td><?php echo $salesmanAdd->address;?></td>
		<td><?php echo $salesmanAdd->city;?></td>
		<td><?php echo $salesmanAdd->state;?></td>
		<td><?php echo $salesmanAdd->country;?></td>
		<td><?php echo $salesmanAdd->zipcode;?></td>
		<td><?php echo $salesmanAdd->salesman_id;?></td>
		
		 
	</tr>
</table>
</body>
</html>