 <?php
$result = $this->payment;
?> 

	<form action="<?php echo $this->getUrl('payment','save');?>" method="POST">
		<table width="20%">
			<tr>
				<td><h3>Edit PAYMENT</h3></td>
				<td><button class="btn btn-primary">SAVE</button></td>
			</tr>
		</table>
		<table>
			 
			<tr>
				<td>paymentId :</td>
				<td><input type="number" name="payment[payment_id]"
				 value="<?php echo $result->payment_id;?>"></td>
			</tr>
			<tr>
				<th>NAME :</th>
				<td><input  type="text" name="payment[name]" value="<?php echo $result->name;?>"></td>
			</tr>
			<tr>
					<th> Status</th>
					<td> <select name="payment[status]" >
						<?php foreach ($result->getResource()->getStatusOptions() as $key => $value): ?>
						<option value="<?php echo $key ?>"><?php echo $value ?></option>
						<?php endforeach; ?>
						
					</select> </td>
				</tr>
			
			 
		</table>
	</form>

