<?php
$payments = $this->getCollection();
?>

	<br/>
	<br/>
		<!-- <div class="alert alert-danger" role="alert"> -->
			<?php echo $this->getTitle(); ?>
		<button class="btn btn-primary" type="submit">
			<?php foreach($this->getButtons() as $key => $button) :?>
					<a class="btn btn-primary" href="<?php echo $button['url']; ?>"><?php echo $button['title']; ?>
					</a>
			<?php endforeach; ?>
		</button>
		</tr>
	</table>
	<br/>
	<br/>
	<table class="table table-success table-striped">
		<?php if (!$payments): ?>
		<tr>
			<td colspan="8" align="center"><b>No data found.</b></td>
		</tr>
		<?php else: ?>

		<tr align="center">
			<?php foreach ($this->getColumns() as $key => $column) : ?>
				<th><?php echo $column['title']; ?></th>
			<?php endforeach; ?>

			<?php foreach ($this->getActions() as $key => $action) : ?>
				<th><?php echo $action['title']; ?></th>
			<?php endforeach; ?>
		</tr>

		<?php foreach ($payments as $payment) : ?>
		<tr align="center">

			<?php foreach($this->getColumns() as $key => $column): ?>
				<td><?php echo $this->getColumnValue($payment, $key); ?></td>
			<?php endforeach; ?>

			<?php foreach($this->getActions() as $key => $action): ?>
				<td><a href="<?php $method = $action['method']; echo $this->$method($row, $key); ?>"><?php echo $action['title'];?></a></td>
			<?php endforeach; ?>
		
		</tr>
		<?php endforeach; ?>
		<?php endif; ?>
	</table>
</body>
</html>